_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
batch_size:
    value: 8
chunk_size:
    value: 4096
device:
    value: cuda
group_size:
    value: 32
learning_rate:
    value: 0.001
num_classes:
    value: 5
num_epochs:
    value: 500
num_group:
    value: 64
num_points:
    value: 4096
num_workers:
    value: 0
overlap:
    value: 1024
transformer_config:
    value:
        depth: 12
        drop_path_rate: 0.1
        encoder_dims: 384
        num_heads: 6
        trans_dim: 384
